#############################################################################
# Makefile for building: test_widget
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 12 08:19:35 2014
# Project:  test_widget.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile test_widget.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQESP_NO_UDEV -D__linux__ -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/include/qt4/QtTest -I3rdparty/qextserialport/src -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtTest -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = 3rdparty/qextserialport/src/qextserialport.cpp \
		3rdparty/qextserialport/src/qextserialenumerator.cpp \
		3rdparty/qextserialport/src/qextserialport_unix.cpp \
		3rdparty/qextserialport/src/qextserialenumerator_linux.cpp \
		main.cpp \
		FlowLayout.cpp \
		panel_info.cpp \
		panel_about.cpp \
		panel_serial.cpp \
		panel_item.cpp \
		panel_setup.cpp \
		panel_detail.cpp \
		mainwin.cpp \
		panel_control.cpp moc_panel_info.cpp \
		moc_panel_about.cpp \
		moc_panel_serial.cpp \
		moc_panel_item.cpp \
		moc_panel_setup.cpp \
		moc_panel_detail.cpp \
		moc_mainwin.cpp \
		moc_panel_control.cpp \
		qrc_res.cpp
OBJECTS       = qextserialport.o \
		qextserialenumerator.o \
		qextserialport_unix.o \
		qextserialenumerator_linux.o \
		main.o \
		FlowLayout.o \
		panel_info.o \
		panel_about.o \
		panel_serial.o \
		panel_item.o \
		panel_setup.o \
		panel_detail.o \
		mainwin.o \
		panel_control.o \
		moc_panel_info.o \
		moc_panel_about.o \
		moc_panel_serial.o \
		moc_panel_item.o \
		moc_panel_setup.o \
		moc_panel_detail.o \
		moc_mainwin.o \
		moc_panel_control.o \
		qrc_res.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		3rdparty/qextserialport/src/qextserialport.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		test_widget.pro
QMAKE_TARGET  = test_widget
DESTDIR       = 
TARGET        = test_widget

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_control_panel.h ui_panel_info.h ui_panel_about.h ui_panel_serial.h ui_panel_item.h ui_panel_setup.h ui_panel_detail.h ui_panel_control.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test_widget.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		3rdparty/qextserialport/src/qextserialport.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qtestlib.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtTest.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile test_widget.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
3rdparty/qextserialport/src/qextserialport.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qtestlib.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtTest.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile test_widget.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test_widget1.0.0 || $(MKDIR) .tmp/test_widget1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test_widget1.0.0/ && $(COPY_FILE) --parents 3rdparty/qextserialport/src/qextserialport.h 3rdparty/qextserialport/src/qextserialenumerator.h 3rdparty/qextserialport/src/qextserialport_global.h 3rdparty/qextserialport/src/qextserialport_p.h 3rdparty/qextserialport/src/qextserialenumerator_p.h FlowLayout.hpp panel_info.h panel_about.h panel_serial.h panel_item.h panel_setup.h panel_detail.h main.h mainwin.h panel_control.h .tmp/test_widget1.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/test_widget1.0.0/ && $(COPY_FILE) --parents 3rdparty/qextserialport/src/qextserialport.cpp 3rdparty/qextserialport/src/qextserialenumerator.cpp 3rdparty/qextserialport/src/qextserialport_unix.cpp 3rdparty/qextserialport/src/qextserialenumerator_linux.cpp main.cpp FlowLayout.cpp panel_info.cpp panel_about.cpp panel_serial.cpp panel_item.cpp panel_setup.cpp panel_detail.cpp mainwin.cpp panel_control.cpp .tmp/test_widget1.0.0/ && $(COPY_FILE) --parents control_panel.ui panel_info.ui panel_about.ui panel_serial.ui panel_item.ui panel_setup.ui panel_detail.ui panel_control.ui .tmp/test_widget1.0.0/ && (cd `dirname .tmp/test_widget1.0.0` && $(TAR) test_widget1.0.0.tar test_widget1.0.0 && $(COMPRESS) test_widget1.0.0.tar) && $(MOVE) `dirname .tmp/test_widget1.0.0`/test_widget1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test_widget1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qextserialport.cpp moc_qextserialenumerator.cpp moc_panel_info.cpp moc_panel_about.cpp moc_panel_serial.cpp moc_panel_item.cpp moc_panel_setup.cpp moc_panel_detail.cpp moc_mainwin.cpp moc_panel_control.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qextserialport.cpp moc_qextserialenumerator.cpp moc_panel_info.cpp moc_panel_about.cpp moc_panel_serial.cpp moc_panel_item.cpp moc_panel_setup.cpp moc_panel_detail.cpp moc_mainwin.cpp moc_panel_control.cpp
moc_qextserialport.cpp: 3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialport.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) 3rdparty/qextserialport/src/qextserialport.h -o moc_qextserialport.cpp

moc_qextserialenumerator.cpp: 3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialenumerator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) 3rdparty/qextserialport/src/qextserialenumerator.h -o moc_qextserialenumerator.cpp

moc_panel_info.cpp: FlowLayout.hpp \
		panel_info.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_info.h -o moc_panel_info.cpp

moc_panel_about.cpp: panel_about.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_about.h -o moc_panel_about.cpp

moc_panel_serial.cpp: panel_serial.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_serial.h -o moc_panel_serial.cpp

moc_panel_item.cpp: panel_info.h \
		FlowLayout.hpp \
		panel_item.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_item.h -o moc_panel_item.cpp

moc_panel_setup.cpp: panel_setup.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_setup.h -o moc_panel_setup.cpp

moc_panel_detail.cpp: panel_info.h \
		FlowLayout.hpp \
		panel_detail.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_detail.h -o moc_panel_detail.cpp

moc_mainwin.cpp: mainwin.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwin.h -o moc_mainwin.cpp

moc_panel_control.cpp: panel_control.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) panel_control.h -o moc_panel_control.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		res/spk_blue_on.png \
		res/bg1.png \
		res/spk_blue_off.png \
		res/mail_1_close.png \
		res/navtex.png \
		res/mail_1_open.png
	/usr/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_control_panel.h ui_panel_info.h ui_panel_about.h ui_panel_serial.h ui_panel_item.h ui_panel_setup.h ui_panel_detail.h ui_panel_control.h
compiler_uic_clean:
	-$(DEL_FILE) ui_control_panel.h ui_panel_info.h ui_panel_about.h ui_panel_serial.h ui_panel_item.h ui_panel_setup.h ui_panel_detail.h ui_panel_control.h
ui_control_panel.h: control_panel.ui
	/usr/bin/uic-qt4 control_panel.ui -o ui_control_panel.h

ui_panel_info.h: panel_info.ui
	/usr/bin/uic-qt4 panel_info.ui -o ui_panel_info.h

ui_panel_about.h: panel_about.ui
	/usr/bin/uic-qt4 panel_about.ui -o ui_panel_about.h

ui_panel_serial.h: panel_serial.ui
	/usr/bin/uic-qt4 panel_serial.ui -o ui_panel_serial.h

ui_panel_item.h: panel_item.ui
	/usr/bin/uic-qt4 panel_item.ui -o ui_panel_item.h

ui_panel_setup.h: panel_setup.ui
	/usr/bin/uic-qt4 panel_setup.ui -o ui_panel_setup.h

ui_panel_detail.h: panel_detail.ui
	/usr/bin/uic-qt4 panel_detail.ui -o ui_panel_detail.h

ui_panel_control.h: panel_control.ui
	/usr/bin/uic-qt4 panel_control.ui -o ui_panel_control.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

qextserialport.o: 3rdparty/qextserialport/src/qextserialport.cpp 3rdparty/qextserialport/src/qextserialport.h \
		3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialport_p.h \
		moc_qextserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o 3rdparty/qextserialport/src/qextserialport.cpp

qextserialenumerator.o: 3rdparty/qextserialport/src/qextserialenumerator.cpp 3rdparty/qextserialport/src/qextserialenumerator.h \
		3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialenumerator_p.h \
		moc_qextserialenumerator.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator.o 3rdparty/qextserialport/src/qextserialenumerator.cpp

qextserialport_unix.o: 3rdparty/qextserialport/src/qextserialport_unix.cpp 3rdparty/qextserialport/src/qextserialport.h \
		3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialport_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport_unix.o 3rdparty/qextserialport/src/qextserialport_unix.cpp

qextserialenumerator_linux.o: 3rdparty/qextserialport/src/qextserialenumerator_linux.cpp 3rdparty/qextserialport/src/qextserialenumerator.h \
		3rdparty/qextserialport/src/qextserialport_global.h \
		3rdparty/qextserialport/src/qextserialenumerator_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialenumerator_linux.o 3rdparty/qextserialport/src/qextserialenumerator_linux.cpp

main.o: main.cpp main.h \
		mainwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

FlowLayout.o: FlowLayout.cpp FlowLayout.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlowLayout.o FlowLayout.cpp

panel_info.o: panel_info.cpp ui_panel_info.h \
		FlowLayout.hpp \
		panel_item.h \
		panel_info.h \
		main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_info.o panel_info.cpp

panel_about.o: panel_about.cpp panel_about.h \
		ui_panel_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_about.o panel_about.cpp

panel_serial.o: panel_serial.cpp 3rdparty/qextserialport/src/qextserialport.h \
		3rdparty/qextserialport/src/qextserialport_global.h \
		panel_serial.h \
		ui_panel_serial.h \
		panel_info.h \
		FlowLayout.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_serial.o panel_serial.cpp

panel_item.o: panel_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_item.o panel_item.cpp

panel_setup.o: panel_setup.cpp panel_setup.h \
		ui_panel_setup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_setup.o panel_setup.cpp

panel_detail.o: panel_detail.cpp panel_detail.h \
		panel_info.h \
		FlowLayout.hpp \
		ui_panel_detail.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_detail.o panel_detail.cpp

mainwin.o: mainwin.cpp FlowLayout.hpp \
		panel_control.h \
		panel_info.h \
		panel_serial.h \
		panel_setup.h \
		panel_about.h \
		panel_detail.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwin.o mainwin.cpp

panel_control.o: panel_control.cpp ui_panel_control.h \
		main.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panel_control.o panel_control.cpp

moc_panel_info.o: moc_panel_info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_info.o moc_panel_info.cpp

moc_panel_about.o: moc_panel_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_about.o moc_panel_about.cpp

moc_panel_serial.o: moc_panel_serial.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_serial.o moc_panel_serial.cpp

moc_panel_item.o: moc_panel_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_item.o moc_panel_item.cpp

moc_panel_setup.o: moc_panel_setup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_setup.o moc_panel_setup.cpp

moc_panel_detail.o: moc_panel_detail.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_detail.o moc_panel_detail.cpp

moc_mainwin.o: moc_mainwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwin.o moc_mainwin.cpp

moc_panel_control.o: moc_panel_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panel_control.o moc_panel_control.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

