######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 4 08:50:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              3rdparty/qextserialport/src \
              3rdparty/qextserialport/examples/enumerator \
              3rdparty/qextserialport/examples/event \
              3rdparty/qextserialport/examples/qespta \
              3rdparty/qextserialport/examples/uartassistant
INCLUDEPATH += . \
               3rdparty/qextserialport/src \
               3rdparty/qextserialport/examples/event \
               3rdparty/qextserialport/examples/qespta \
               3rdparty/qextserialport/examples/uartassistant

# Input
HEADERS += control_panel.h \
           FlowLayout.hpp \
           myserialport.h \
           panel_about.h \
           panel_detail.h \
           panel_info.h \
           panel_item.h \
           panel_serial.h \
           panel_setup.h \
           3rdparty/qextserialport/src/qextserialenumerator.h \
           3rdparty/qextserialport/src/qextserialenumerator_p.h \
           3rdparty/qextserialport/src/qextserialport.h \
           3rdparty/qextserialport/src/qextserialport_global.h \
           3rdparty/qextserialport/src/qextserialport_p.h \
           3rdparty/qextserialport/examples/event/PortListener.h \
           3rdparty/qextserialport/examples/qespta/MainWindow.h \
           3rdparty/qextserialport/examples/qespta/MessageWindow.h \
           3rdparty/qextserialport/examples/qespta/QespTest.h \
           3rdparty/qextserialport/examples/uartassistant/dialog.h \
           3rdparty/qextserialport/examples/uartassistant/hled.h \
           moc_qextserialport.cpp
FORMS += control_panel.ui \
         listwidget_item.ui \
         navtex_item.ui \
         panel_about.ui \
         panel_detail.ui \
         panel_info.ui \
         panel_item.ui \
         panel_serial.ui \
         panel_setup.ui \
         3rdparty/qextserialport/examples/uartassistant/dialog.ui
SOURCES += about_panel.cpp \
           control_panel.cpp \
           FlowLayout.cpp \
           main.cpp \
           myserialport.cpp \
           panel_about.cpp \
           panel_detail.cpp \
           panel_info.cpp \
           panel_item.cpp \
           panel_serial.cpp \
           panel_setup.cpp \
           3rdparty/qextserialport/src/qextserialenumerator.cpp \
           3rdparty/qextserialport/src/qextserialenumerator_linux.cpp \
           3rdparty/qextserialport/src/qextserialenumerator_osx.cpp \
           3rdparty/qextserialport/src/qextserialenumerator_unix.cpp \
           3rdparty/qextserialport/src/qextserialenumerator_win.cpp \
           3rdparty/qextserialport/src/qextserialport.cpp \
           3rdparty/qextserialport/src/qextserialport_unix.cpp \
           3rdparty/qextserialport/src/qextserialport_win.cpp \
           3rdparty/qextserialport/examples/enumerator/main.cpp \
           3rdparty/qextserialport/examples/event/main.cpp \
           3rdparty/qextserialport/examples/event/PortListener.cpp \
           3rdparty/qextserialport/examples/qespta/main.cpp \
           3rdparty/qextserialport/examples/qespta/MainWindow.cpp \
           3rdparty/qextserialport/examples/qespta/MessageWindow.cpp \
           3rdparty/qextserialport/examples/qespta/QespTest.cpp \
           3rdparty/qextserialport/examples/uartassistant/dialog.cpp \
           3rdparty/qextserialport/examples/uartassistant/hled.cpp \
           3rdparty/qextserialport/examples/uartassistant/main.cpp
RESOURCES += res.qrc
